### ISSUE TITLE
Stack failure after updating annotation on node

### ISSUE THREAD

**Issue by IBMRob** [jackfrancis/kamino#49]
Running the following helm command
```
helm install --repo https://jackfrancis.github.io/kamino/ \
  update-from-aks-agentpool-13184734-vmss000000 \
  vmss-prototype --namespace default \
  --set kamino.scheduleOnControlPlane=false \
  --set kamino.newUpdatedNodes=3 \
  --set kamino.targetNode=aks-agentpool-13184734-vmss000000
```

resulted in the following stack and error
```
.......
INFO: ===> Executing command: ['kubectl' 'drain' '--ignore-daemonsets' '--delete-local-data' '--force' '--grace-period' '300' '--timeout' '900s' 'aks-agentpool-13184734-vmss000000'] #  ... try #3
INFO: ===> Completed in 24.51s: ['kubectl' 'drain' '--ignore-daemonsets' '--delete-local-data' '--force' '--grace-period' '300' '--timeout' '900s' 'aks-agentpool-13184734-vmss000000'] # RC=1
INFO: ===> Executing command: ['kubectl' 'uncordon' 'aks-agentpool-13184734-vmss000000']
INFO: ===> Executing command: ['kubectl' 'annotate' 'node' 'aks-agentpool-13184734-vmss000000' 'cluster-autoscaler.kubernetes.io/scale-down-disabled-']
Traceback (most recent call last):
  File "/usr/bin/vmss-prototype", line 1435, in <module>
    main()
  File "/usr/bin/vmss-prototype", line 1430, in main
    cmd_line_args.func(cmd_line_args)
  File "/usr/bin/vmss-prototype", line 1259, in <lambda>
    parser.set_defaults(func=lambda sub_args: in_cluster(sub_args, func))
  File "/usr/bin/vmss-prototype", line 1130, in in_cluster
    return func(sub_args)
  File "/usr/bin/vmss-prototype", line 694, in vmss_prototype_update
    fatal_error('Could not drain node {0}', target_node)
TypeError: fatal_error() takes 1 positional argument but 2 were given
```

**Comment by Michael-Sinz** [comment]
Thanks - the error is actually that the node failed to drain but there was a silly syntax error in that code path.

**Comment by Michael-Sinz** [comment]
Upon failure to drain, there are two paths - one is the "force" path where we do a forced drain and the other is the graceful path where we return the node to service and render an error that the selected node can not be drained.

Unfortunately, the rendering of that message had a mistake in it so it failed in rendering the failure message.

I have PR https://github.com/jackfrancis/kamino/pull/52 set to fix the typo there.

Thank you again for reporting this.
